version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "Installing SAM CLI"
      - pip install aws-sam-cli
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building SAM application"
      - sam build
      - echo "Packaging SAM application"
      - sam package --s3-bucket $ARTIFACTS_BUCKET --output-template-file packaged-template.yaml
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - packaged-template.yaml  # Changed from template.yaml



