AWSTemplateFormatVersion: '2010-09-09'
Description: Java SAM Pipeline

Parameters:
  GitHubConnectionArn:
    Type: String
  RepositoryName:
    Type: String
  BranchName:
    Type: String

Resources:

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess

      Policies:
        - PolicyName: PipelineS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetBucketVersioning
                Resource:
                  - !Sub arn:aws:s3:::codepipeline-artifacts-${AWS::AccountId}-${AWS::Region}/*
                  - !Sub arn:aws:s3:::codepipeline-artifacts-${AWS::AccountId}-${AWS::Region}

  CodeBuildRole:
     Type: AWS::IAM::Role
     Properties:
       AssumeRolePolicyDocument:
         Version: '2012-10-17'
         Statement:
           - Effect: Allow
             Principal:
               Service: codebuild.amazonaws.com
             Action: sts:AssumeRole
       Policies:
         - PolicyName: CodeBuildLoggingPolicy
           PolicyDocument:
             Version: '2012-10-17'
             Statement:
               # CloudWatch Logs (REQUIRED)
               - Effect: Allow
                 Action:
                   - logs:CreateLogGroup
                   - logs:CreateLogStream
                   - logs:PutLogEvents
                 Resource: "*"
                # CodePipeline artifact bucket (REQUIRED)
               - Effect: Allow
                 Action:
                   - s3:GetObject
                   - s3:GetObjectVersion
                   - s3:GetBucketLocation
                   - s3:PutObject
                 Resource:
                   - !Sub "arn:aws:s3:::codepipeline-artifacts-${AWS::AccountId}-${AWS::Region}/*"
                # Report status back to CodePipeline
               - Effect: Allow
                 Action:
                   - codepipeline:PutJobSuccessResult
                   - codepipeline:PutJobFailureResult
                 Resource: "*"
 
  CloudFormationDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com  # CloudFormation role
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudFormationDeployPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'iam:*'
                  - 'lambda:*'
                  - 'apigateway:*'
                  - 's3:*'
                  - 'logs:*'
                  - 'events:*'
                  - 'cloudformation:*'
                Resource: '*'

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "codepipeline-artifacts-${AWS::AccountId}-${AWS::Region}"

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: JavaSAMBuild
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      TimeoutInMinutes: 60

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: JavaSAMPipeline
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket

      Stages:

        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref GitHubConnectionArn
                FullRepositoryId: !Ref RepositoryName
                BranchName: !Ref BranchName
              OutputArtifacts:
                - Name: SourceOutput

        - Name: Build
          Actions:
            - Name: BuildSAM
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: JavaSAMBuild

        - Name: DeployUS
          Actions:
            - Name: DeploySAM
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                TemplatePath: BuildOutput::template.yaml
                RoleArn: !GetAtt CloudFormationDeployRole.Arn
                StackName: JavaSAMApp
                Capabilities: CAPABILITY_IAM
                

Outputs:
  PipelineName:
    Value: JavaSAMPipeline
