AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless Task Processing Pipeline (API → SQS → Worker → S3/DynamoDB)

Globals:
  Function:
    Runtime: java17
    MemorySize: 1024
    Timeout: 30
    Architectures:
      - x86_64

#Parameters:
#  OutputBucketName:
#    Type: String
#    Description: Name of the existing S3 bucket for output files

Resources:

  OutputBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${AWS::StackName}-output-bucket-${AWS::AccountId}"
      # Add any other bucket configuration you need
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # --------------------------------------
  #  SQS QUEUE
  # --------------------------------------
  TaskQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-TaskQueue"  # Make it unique like your bucket
      VisibilityTimeoutSeconds: 300                  # Adjust based on processing time
      MessageRetentionPeriod: 1209600               # 14 days (default)
      RedrivePolicy:                                # Dead letter queue for failed messages
        deadLetterTargetArn: !GetAtt TaskDLQ.Arn
        maxReceiveCount: 3

  TaskDLQ:  # Dead Letter Queue for failed messages
     Type: AWS::SQS::Queue
     Properties:
       QueueName: !Sub "${AWS::StackName}-TaskQueue-DLQ"

#  TasksTable:
#    Type: AWS::DynamoDB::Table
#    Properties:
#      TableName: !Sub "${AWS::StackName}-TasksTable"
#      BillingMode: PAY_PER_REQUEST    # Or PROVISIONED with ReadCapacityUnits/WriteCapacityUnits
#      AttributeDefinitions:
#        - AttributeName: taskId
#          AttributeType: S
#      KeySchema:
#        - AttributeName: taskId
#        KeyType: HASH


  # --------------------------------------
  #  API LAMBDA FUNCTION
  # --------------------------------------
  ApiLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-ApiLambdaFunction"  # Make it unique
      Handler: com.art.batch.controller.ApiLambdaHandler::handleRequest
      Runtime: java17                    # ✅ Added required runtime
      CodeUri: .
      Timeout: 30                       # ✅ Add timeout (default is 3 seconds)
      MemorySize: 512                   # ✅ Add memory size
      Environment:
        Variables:
          QUEUE_URL: !Ref TaskQueue
          TASK_TABLE: "TasksTable"   # ✅ Reference the actual table
          OUTPUT_BUCKET: !Ref OutputBucket
      Policies:
        - DynamoDBCrudPolicy:
          TableName: "TasksTable"  # ✅ Reference the table
        - SQSSendMessagePolicy:
          QueueName: !Ref TaskQueue   # ✅ Reference the queue
        - S3WritePolicy:
          BucketName: !Ref OutputBucket
      Events:                          # ✅ Add API Gateway trigger
        ApiEvent:
          Type: Api
          Properties:
            Path: /tasks
            Method: post
      DeadLetterQueue:                 # ✅ Add DLQ for failed invocations
        Type: SQS
        TargetArn: !GetAtt ApiDLQ.Arn


  # --------------------------------------
  #  WORKER LAMBDA FUNCTION
  # --------------------------------------
  WorkerLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-WorkerLambdaFunction"
      Handler: com.art.batch.controller.WorkerLambdaHandler::handleRequest
      Runtime: java17                    # ✅ Added required runtime
      CodeUri: .
      Timeout: 300                       # ✅ 5 minutes for processing tasks
      MemorySize: 1024                   # ✅ More memory for worker tasks
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref OutputBucket
          TASK_TABLE: "TasksTable"    # ✅ Reference the actual table
      Policies:
          - DynamoDBCrudPolicy:
            TableName: "TasksTable"   # ✅ Reference the table
          - S3WritePolicy:
            BucketName: !Ref OutputBucket

      Events:
        TaskQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt TaskQueue.Arn
            BatchSize: 1                 # ✅ Good for individual processing
            MaximumBatchingWindowInSeconds: 5  # ✅ Optional: reduce latency
            FunctionResponseTypes:
              - ReportBatchItemFailures
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt WorkerDLQ.Arn


Outputs:
  ApiLambdaArn:
    Value: !GetAtt ApiLambdaFunction.Arn
    Description: ARN of the API Lambda function

  WorkerLambdaArn:
    Value: !GetAtt WorkerLambdaFunction.Arn
    Description: ARN of the Worker Lambda function

  QueueUrl:
    Value: !Ref TaskQueue
    Description: SQS queue URL

  QueueArn:
    Value: !GetAtt TaskQueue.Arn
    Description: SQS queue ARN

  OutputBucketName:
    Value: !Ref OutputBucket
    Description: Name of the S3 output bucket
    Export:
      Name: !Sub "${AWS::StackName}-OutputBucket"

  TaskTableName:
    Value: "TasksTable"
    Description: Name of the DynamoDB tasks table

  ApiEndpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Description: API Gateway endpoint URL
    Export:
      Name: !Sub "${AWS::StackName}-ApiEndpoint"
